<?php

/**
 * @file
 * The module for importing pinterest pins.
 */

/*
 * The API passes in a $user object that contains four properties:
 * uid, userid, password, feed. These properties contain the account
 * information entered into the user's settings page, along with the 
 * uid of their Drupal account.
 */
function activitystream_pinterest_streamapi($user) {
  // This user doesn't have a pinterest ID entered
  if (!$user->userid) {
    return;
  }

  // Use the activitystream_feed module to pull in the user's
  // history. 
  $user->feed = 'http://pinterest.com/'. $user->userid .'/feed.rss';
  $items = activitystream_feed_streamapi($user);
  return $items;
}


/*
 * Implement a user settings form hook. Modules should build a form
 * using an array that mirrors the Drupal form API. activitystream.module
 * will add the form elements to a tab called Activity Streams on the
 * user's Profile Edit page. Fields should be named
 * yourmodulename_fieldname. For instance, to store the user ID for 
 * Flickr, the field name is activitystream_flickr_userid
 *
 * To avoid collisions with other activitystream module's forms
 * use your module's name as the form array's key.
 *
 * @param $edit
 *   The values of the form fields, used for setting defaults
 * 
 */
function activitystream_pinterest_activitystream_settings(&$edit) {
  $form['activitystream_pinterest'] = array(
    '#type' => 'fieldset',
    '#title' => t('Pinterest settings'));
  $form['activitystream_pinterest']['activitystream_pinterest_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('Username'),
    '#default_value' => empty($edit['activitystream_pinterest_userid']) ? '' : $edit['activitystream_pinterest_userid'],
    '#description' => t('Your pinterest username'));
  return $form;  
}

function theme_activitystream_pinterest_icon() {
  return theme_image(drupal_get_path('module', 'activitystream_pinterest') .'/pinterest.png', 'Pinterest');
}

function theme_activitystream_pinterest_item($activity) {
  $node = node_load($activity->nid);
  $date = theme('activitystream_date', $node->created);
  $user = user_load(array('uid' => $node->uid));
  $name = theme('activitystream_username', $user);
  
  return '<span class="activitystream-item">'. theme('activitystream_pinterest_icon') . " <span>$name " . t('pinned') . " " . l('<img src="' . $activity->link . '" alt="' . $node->title . '"/>', $activity->link, array('html'=>TRUE)) . " <span class=\"activitystream-created\">$date</span></span></span>";
}

function activitystream_pinterest_theme() {
  return array(
    'activitystream_pinterest_icon' => array(
      'arguments' => array(),
    ),
    'activitystream_pinterest_item' => array(
      'arguments' => array('activity' => NULL),
    ),
  );
}

